# Generated by Django 4.1.7 on 2023-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_sex',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
