# Generated by Django 4.1.7 on 2023-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery/')),
                ('text', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
