# Generated by Django 4.1.5 on 2023-07-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_link_remove_dog_link_alter_dog_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
