# Generated by Django 4.1.7 on 2023-07-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
