# Generated by Django 4.1.7 on 2023-07-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
